### ISSUE TITLE
你创建这个干啥叻？

### ISSUE THREAD

**Issue by pkumza** [lynnlyc/homepage#1]
Just readme.md

**Comment by lynnlyc** [comment]
It is my under-construction homepage.

 

 

发件人: pkumza [mailto:notifications@github.com] 
发送时间: 2015年9月27日 16:06
收件人: lynnlyc/homepage <homepage@noreply.github.com>
主题: [homepage] 你创建这个干啥叻？ (#1)

 

Just readme.md
